apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythontest
  labels:
    app: pythontest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythontest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pythontest
    spec:
      containers:
        - name: pythontest
          image: localhost:4000/pythontest:latest
          ports:
            - containerPort: 5000
              name: microport

---
apiVersion: v1
kind: Service
metadata:
  name: pythontest
  labels:
    app: pythontest
spec:
  type: NodePort
  selector:
    app: pythontest
  ports:
    - port: 5000       # Service port
      targetPort: 5000 # Container port
      nodePort: 31000  # Exposed port on Node
